### ISSUE TITLE
Where does the plugin gets the diff ?

### ISSUE THREAD

**Issue by giovanisp** [troosan/sonar-scm-jazzrtc#10]
How dows the plugin gets the information about changes made in the files (diff) and/or duplications ? Sonarqube is not calculating "Duplications on new code" at the moment.

**Comment by henryju** [comment]
This plugin is supposed to provide the "blame" of each analyzed file. Blame = for each line, return the date + author login of the the last modification.

**Comment by giovanisp** [comment]
thanks, could you explain how it calculates then the "Duplications on new code %".
I can see new bugs, new vulnerabilities, new code smells,... but duplications on new code is always a dash "-" (like if it was disabled). Any hints on where to look at ?

**Comment by henryju** [comment]
Do you correctly see blame information (= author, commit id and commit date) in SonarQube code viewer? New issues measures are computed in a different way that doesn't rely on SCM. Only new duplications/new coverage is relying on SCM.

**Comment by giovanisp** [comment]
Hi, yes I see the blame info in SQ code viewer (both on 6.x and 5.6.7):
![image](https://user-images.githubusercontent.com/180794/32841004-9084181a-ca19-11e7-9600-6c870196f9e7.png)


It seems under 6.x something's not working on the calculations for new LOC and New Duplications %. I got it working on 5.6.7 but the same analysis on 6.4 isn't producing the same numbers. Could it be that returning "zero" LOC on new code on sonar 6.x leads to an error in calculating % dup. lines ?

**5.6.7**
![image](https://user-images.githubusercontent.com/180794/32841026-9acae240-ca19-11e7-90ec-71bee71c628f.png)

**6.4**
![image](https://user-images.githubusercontent.com/180794/32841394-79810cee-ca1a-11e7-84d4-57e32f2b60cb.png)
![image](https://user-images.githubusercontent.com/180794/32841411-82fb0afe-ca1a-11e7-8c8e-4e693ca968d4.png)

**Comment by loop01** [comment]
Hello, i have the same problem!
Any news?

Thanks.

**Comment by giovanisp** [comment]
@henryju do you have any guesses on where the problem may lie in how sonar 6.x counts new LOCs and passes it to the plugin ?

**Comment by henryju** [comment]
The new lines is computed very simply: a line is new if the blame date is after the start of the leak period. What is the start of you leak period? Do you have some lines updated after this date?

**Comment by giovanisp** [comment]
Yes, I have checked that.
Do you know if the current version of the plug-in works/is compatible with sonar 6.3/6.4 ?

**Comment by troosan** [comment]
Latest version is compatible with 7.7 and later
