### ISSUE TITLE
Plugin does not work with SonarQube 7.4

### ISSUE THREAD

**Issue by PietroLubini** [troosan/sonar-scm-jazzrtc#13]
Plugin crashes SonarQube 7.4.

Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin Jazz RTC [scmjazzrtc]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)

**Comment by henryju** [comment]
This is related to #11
