### ISSUE TITLE
lscm annotate error

### ISSUE THREAD

**Issue by cgaiani** [troosan/sonar-scm-jazzrtc#21]
Hi,
SonarQube v 7.9
We are trying to use sonar.scm.provider=jazz during our analysis of application stored on RTC repository.
We need to use it in order to be more precise during calculation of NewCode.
We have installed sonar-scm-jazzrtc-plugin-1.2.jar plugin and configured analysis in order to use sonar.scm.provider=jazz parameter.

During analysis (in debug mode) we have following error:
...
17:42:34.979 DEBUG: Executing: cmd /C call lscm annotate ///C:/Program Files (x86)/Jenkins/workspace/NuovoFlussoProduzione/AnalisiAcronimiProduzioneRTC/SRC/BolloAutoWS/src/com/etasistemi/webservice/BolloAutoWebService.java
17:42:35.244 DEBUG: Skipping untracked file: ///C:/Program Files (x86)/Jenkins/workspace/NuovoFlussoProduzione/AnalisiAcronimiProduzioneRTC/SRC/BolloAutoWS/src/com/etasistemi/webservice/BolloAutoWebService.java. Annotate command exit code: 3
...
17:42:39.042 INFO: 0/24 files analyzed
17:42:39.042 WARN: Missing blame information for the following files:
...
17:42:39.058 WARN: * SRC/BolloAutoWS/src/com/etasistemi/webservice/BolloAutoWebService.java
...

Have you some idea about the problem?

Many Thanks

Regards

Claudio

**Comment by troosan** [comment]
Unfortunately, exit code 3 means "A failure occurred for an unknown reason"
https://www.ibm.com/support/knowledgecenter/SSYMRC_7.0.1/com.ibm.team.scm.doc/topics/r_scm_cli_retcodes.html
Maybe because of Jenkins being installed in C:/Program Files (x86) ??
